name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y \
        libgl1-mesa-dev \
        libgles2-mesa-dev \
        libsdl2-dev \
        libsdl2-image-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev \
        libportmidi-dev \
        libswscale-dev \
        libavformat-dev \
        libavcodec-dev \
        zlib1g-dev \
        build-essential \
        git \
        zip \
        unzip \
        autoconf \
        automake \
        libtool \
        pkg-config \
        python3-setuptools \
        python3-pip

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade cython
        pip install buildozer

    - name: Build APK with Buildozer
      run: |
        cd ${{ github.workspace }}
        buildozer init
        sed -i 's/# (list) Application requirements/(list) Application requirements\nrequirements = python3,kivy,opencv,mediapipe/g' buildozer.spec
        sed -i 's/# (str) Title of the application (max 13 characters)/(str) Title of the application\ntitle = MyApp/g' buildozer.spec
        sed -i 's/# (str) Package name/(str) Package name\npackage.name = myapp/g' buildozer.spec
        sed -i 's/# (str) Package domain/(str) Package domain\ndomain = org.myapp/g' buildozer.spec
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: myapp.apk
        path: bin/*.apk
